import axios from 'axios';
import fs from 'fs';

const cookieString = "_ym_uid=1774571187589330676; _ym_d=1774571187; _ym_isad=2; stc=EAAdABYAEAA=; ta=AgAOAA8ABgAIAA==; acb=AgAOAA8ABgAIAA==; hrl=AgAOAA8ABgAIAA==; cookieConsent=EAAdABYAEAA=; remember_web_59ba36addc2b2f9401580f014c7f58ea4e30989d=eyJpdiI6IkN5MERSaVdseWVmQmRRSlJrOVFVdnc9PSIsInZhbHVlIjoibVFpY3R5RFpnTDE4L0tra2IwNEdSa0I0Ty9EM1VVR0hGcUNVdVBya2NrUFlQMElFTUVkQzNON3FPWkMxRllualFJREErWG5xSGdrbGNvcXRydCtRTHlvRkdhU29hMHYrdFF3QVhEQ0ZKMW42SlQ4NWd0dTcwdVU3RFo5NEZ6VjlFRVZxby9INWsvNXZkOFBkVHZxeEpkTzNSeDgyL0V4VUhNcHpTQnpPUkw4eFRLcHZWWTRzSC8rZkJ2VjBLNWw4ZmZhVDQ2TTlNY3VIVTcxWk84TEtrWG1EM2lIT05ibmw5czg1bExNUGJrYz0iLCJtYWMiOiIzOWI3OWU3NzY0OGRkZmM3MjUyNzU4NWRiMjliNTgwZWI4ZjY1ODNkNzVhZTY5YjJmZTgxODUyMzY3MDE0ZjE4IiwidGFnIjoiIn0%3D; cc=UAA=; sp=HwBNAAoAEQBPAF8ATABDAF0ATQBPAFcACQAMAB0ABAAIAA4AGgA8AAkARwBUAFYAUwBWAEEAWQBPAAYADwAAAAEACAAMAAcAFAAsAAoAVgBeAF4ATwBXABkADQALABkAAQAmAAcAVwBXAFQAXgBEAFcAQwBBABYAIwAEAAMAEQBGAFUAQQBpBF0EJQRUBEwEJARRBFEETwRdBEUAVgRDBFAEWgRYBE0EVARFAFYEVAAnBFAEUwRPBFMEVwRQBE4ERAAuBEMASwRSBFUELwRJBC8EUwRbBFUAXgQlBC0EQwRUBFMEWwRXAEEARwAaADoABQACAAYAVwBXAEcAfwREBFMEUQRRBD4EVARFAFQENwQkBC4EQQBZAE8AFAAgABUACQAKAEEATwBPAH8EXgROBFoEVgRDAEsEUgRVBC8ESQRaBC4EIQRNBE0AWgRQBEAEVgRaBCMERgRdBFAELAQ1BCsETwBRBEsEWQRdBCwEQQRfBCMETwBVAFgEJARVBEwERABdBEMARgQtBCYEWQRKBFYEUQRfBFUAUwQnBFoEQQRfBFoEXgRNBFUERQBTBEQEXgRRBFwETQRWBCQEIQRUAFcEXwRUBFUAVQRSBE4ARQRUBFQEWARLBFAEWwRcBFgARABTBFMENQRXBF0ELgRKBFYEXwReBEgEJgQgBE4ANgRUBFUEWwRJBE0AUgRTBEQEXgRRBF8EVQBTBFoEXgQ1BFkEUQQiBDcEVQRaAEwACQA=; e_activatedPremium=EAAdABYAEAA=; XSRF-TOKEN=eyJpdiI6InVQWi96ZHdUQU1yQkNCRTlMdDFhc2c9PSIsInZhbHVlIjoiN09Ga29TdGNrdUdKT2dEeHVPNWNXNDl5NEZDL2NMMW1WZk1NVmx2YlFaMktoMzhIVkdhM09YTzd0YVNSSTdKYkU3dng0VDRnLzErUkphRndSR0M0WjRiMENUU0w2WGJDaS90Y3BlL3k5eG1QYTdhTHoycGpHOTVKQ0FlN0xGRUgiLCJtYWMiOiJmYjlkZmQ1NjE0ZjE1MzQwNTc2MWY1MmYxODdiNTQyZjc0YTVmOTE0MzEyN2VmM2UzOWViMmU0ODc0MzdkMGQzIiwidGFnIjoiIn0%3D; dopog_bilety_2026_session=eyJpdiI6ImgxUkZScjZWbkRhR1pxb3F4aUZtd1E9PSIsInZhbHVlIjoibnJMU0UwbWZxQ2FyY0RCQWU3MythdG1vbDNBcDFvOTNwSXdYekp0Q1I1SDVINDZJMnNzVWFvaFdjbEdPRHQwekRTc0JoVXkxTlVRbXErcDZ0V0M0MTNaMUcxeklYTWJydkNpMWFyYm1tZWlTZnhIWFZYSFc5WHBqK3JOLzZCbW8iLCJtYWMiOiI3ZWRhYTk5ODU1MjEyZmM4MjBlODQ1Yzg4YjNhNGE0OTk2ZGQzZDZmZTYzMWYyZTIwNjk4ZWFlNDZjMmQ0MTVhIiwidGFnIjoiIn0%3D";

async function run() {
  try {
    const res = await axios.get('https://dopog-exam.ru/8/8001?view=theme', {
      headers: {
        'Cookie': cookieString,
        'User-Agent': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/122.0.0.0 Safari/537.36'
      },
      validateStatus: () => true
    });

    console.log("Status:", res.status);
    fs.writeFileSync('/tmp/theme8.html', res.data);
    
    // Quick test if we are authenticated
    if (res.data.includes('grevelien@yandex.ru')) {
        console.log("Authentication successful! Exported HTML.");
    } else {
        console.log("Authentication might have failed or email not rendered.");
    }

  } catch (err) {
    console.error(err.message);
  }
}

run();
